site_name: Makobot HAUV Documentation
copyright: Copyright (c) 2020 Makobot HAUV developers
site_description: "Makobot HAUV Documentation"
site_url: https://makobot-hauv.github.io/
repo_url: https://github.com/makobot-hauv

theme:
    name: material
    palette:
        primary: light blue
        accent: deep orange
    icon:
        logo: material/library
        repo: fontawesome/brands/git-alt
    features:
        - tabs

plugins:
    - search
    # - awesome-pages

markdown_extensions:
  - codehilite

nav:
    - Home: index.md
    - Quick Start: quickstart.md
    - Bill of Materials: bom.md
    - Hardware:
        - Robot Modification Instructions: hardware/robot_modifications.md
        - Wiring Instructions: hardware/wiring.md
    - Software:
        - Software: software/software.md
        - ROS Installation: software/ros_installation.md
        - Networking Configuration: software/networking.md
        - Fitlet2 Software Installation: software/fitlet_installation.md
        - Jetson TX2 Software Installation: software/jetson_installation.md
    - Simulation:
        - Simulations with UUV Simulator: simulation/simulations.md
    - Field Testing:
        - Field Testing: field-testing/field_testing.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/makobot-hauv
