site_name: Makobot HAUV Documentation
copyright: Copyright (c) 2020 Makobot HAUV developers
site_description: "Makobot HAUV Documentation"
site_url: https://makobot-hauv.github.io/
repo_url: https://github.com/makobot-hauv

theme:
    name: material
    palette:
        primary: light blue
        accent: deep orange
    icon:
        logo: material/library
        repo: fontawesome/brands/git-alt
    features:
        - tabs

plugins:
    - search
    # - awesome-pages

markdown_extensions:
  - codehilite

nav:
    - Home: index.md
    - Quick Start: quickstart.md
    - Bill of Materials: bom.md
    - Hardware:
        - Hardware Modification: hardware/hardware_modifications.md
        - Manufacturing: hardware/manufacturing.md
        - Primary Control Module:
            - Primary Module Modifications: hardware/primary-module/primary-module-mod.md
            - Primary Module Assembly: hardware/primary-module/primary-module-assem.md
        - Power Module:
            - Power Module Manufacturing: hardware/power-module/power-module-mfg.md
            - Power Module Assembly: hardware/power-module/power-module-assem.md
        - Auxiliary Computing Module:
            - Auxiliary Module Manufacturing: hardware/aux-module/aux-module-mfg.md
            - Auxiliary Module Assembly: hardware/aux-module/aux-module-assem.md
        - Camera Modules:
            - Camera Module Manufacturing: hardware/camera-modules/camera-module-mfg.md
            - Camera Module Assembly: hardware/camera-modules/camera-module-assem.md
        - Assembly:
            - Hardware Assembly: hardware/assembly/assembly.md
            - Wiring Instructions: hardware/assembly/wiring.md
        - Testing: hardware/testing.md
    - Software:
        - Software Installation: software/software.md
        - Networking Configuration: software/networking.md
        - Camera Configuration: software/cameraconfig.md
        - Topside Configuration (Optional): software/topside.md
    - Simulation:
        - Simulations with UUV Simulator: simulation/simulations.md
    - Field Testing:
        - Field Testing: field-testing/field_testing.md
    - Diver Rig:
        - Diver Rig: diver-rig/diver-rig.md
        - Bill of Materials: diver-rig/bom.md
        - Manufacturing: diver-rig/mfg.md
        - Assembly: diver-rig/assem.md 

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/makobot-hauv
